# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calC.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# This calculator is not function yet.
# Date of creation: 3/02/2022
# Functionality = Non-functional, it can only display numbers and sign properly, no arithematic function are possible.

# Wait for Future updates for arithematic functionality.


from PyQt5 import QtCore, QtGui, QtWidgets
global numbers
numbers = []

class Ui_MainWindow(object):



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(211, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("7"))
        self.button_7.setGeometry(QtCore.QRect(10, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("8"))
        self.button_8.setGeometry(QtCore.QRect(80, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("9"))
        self.button_9.setGeometry(QtCore.QRect(150, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("4"))
        self.button_4.setGeometry(QtCore.QRect(10, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("5"))
        self.button_5.setGeometry(QtCore.QRect(80, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("6"))
        self.button_6.setGeometry(QtCore.QRect(150, 210, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("1"))
        self.button_1.setGeometry(QtCore.QRect(10, 280, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("2"))
        self.button_2.setGeometry(QtCore.QRect(80, 280, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("3"))
        self.button_3.setGeometry(QtCore.QRect(150, 280, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("C"))
        self.button_clear.setGeometry(QtCore.QRect(10, 90, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.button_add = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("+"))
        self.button_add.setGeometry(QtCore.QRect(90, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.button_sub = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("-"))
        self.button_sub.setGeometry(QtCore.QRect(150, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.button_sub.setFont(font)
        self.button_sub.setObjectName("button_sub")
        self.output_screen = QtWidgets.QLabel(self.centralwidget)
        self.output_screen.setGeometry(QtCore.QRect(10, 15, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_screen.setFont(font)
        self.output_screen.setAutoFillBackground(True)
        self.output_screen.setFrameShape(QtWidgets.QFrame.Box)
        self.output_screen.setText("0")
        self.output_screen.setObjectName("output_screen")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("0"))
        self.button_0.setGeometry(QtCore.QRect(80, 350, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_dot = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_pressed("."))
        self.button_dot.setGeometry(QtCore.QRect(10, 350, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_dot.setFont(font)
        self.button_dot.setObjectName("button_dot")
        self.button_result = QtWidgets.QPushButton(self.centralwidget)
        self.button_result.setGeometry(QtCore.QRect(150, 350, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.button_result.setFont(font)
        self.button_result.setObjectName("button_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_add.setText(_translate("MainWindow", "+"))
        self.button_sub.setText(_translate("MainWindow", "-"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_dot.setText(_translate("MainWindow", "."))
        self.button_result.setText(_translate("MainWindow", "="))

    def button_pressed(self, pressed_button):
        if pressed_button == "C":
            self.output_screen.setText("0")
            numbers.clear()
        else:
            if self.output_screen.text() == "0":
                self.output_screen.setText("")

            self.output_screen.setText(f'{self.output_screen.text()}{pressed_button}')
            if pressed_button == "+" or pressed_button == "-" or pressed_button == "=" or pressed_button == ".":
                numbers.append(pressed_button)
                print(numbers)
            else:
                numbers.append(int(pressed_button))
                print(numbers)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
